#
# This source file is part of the Stanford Spezi open-source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

version: 1
builder:
  configs:
    - platform: ios
      scheme: Spezi
      swift_version: 6
      documentation_targets:
      - Spezi
      - SpeziTesting
