#
# This source file is part of the CardinalKit open-source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

version: 1
builder:
  configs:
    - platform: ios
      documentation_targets:
      - CardinalKit
      - Account
      - Contact
      - FHIR
      - HealthKitDataSource
      - LocalStorage
      - Onboarding
      - Scheduler
      - SecureStorage
      - Views
      - XCTRuntimeAssertions
