#
# This source file is part of the Stanford Spezi open source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: CI-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: StanfordBDHG/.github/.github/workflows/swift-package-ci.yml@v2
    with:
      linux_run_tests: true
    secrets: inherit
